# Generated by Django 4.0.4 on 2022-05-27 20:02

import Germinar.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catProducto',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id categoria')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='catSuscripcion',
            fields=[
                ('idSuscripcion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id suscripcion')),
                ('nombreSuscripcion', models.CharField(choices=[('S', 'Semilla'), ('G', 'Germinar')], max_length=1, verbose_name='Nombre suscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id cliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre cliente')),
                ('contrasenna', models.CharField(max_length=50, verbose_name='Contrasenna')),
                ('correoElect', models.CharField(max_length=70, verbose_name='Correo Electronico')),
                ('fechaNac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('ciudadCliente', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('regionCliente', models.CharField(max_length=50, verbose_name='Region')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion cliente')),
                ('suscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Germinar.catsuscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('idCompra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id compra')),
                ('estadoCompra', models.CharField(choices=[('EE', 'En espera para despacho'), ('EC', 'En camino'), ('R', 'Recibido')], max_length=2)),
                ('total', models.PositiveIntegerField(verbose_name='Total compra')),
                ('descuentoCli', models.CharField(max_length=30, verbose_name=Germinar.models.compra.descuento)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Germinar.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id producto')),
                ('nombreProducto', models.CharField(max_length=150, verbose_name='Nombre del producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Stock del producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Germinar.catproducto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Germinar.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='detalleCompra',
            fields=[
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Germinar.compra')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad de productos')),
                ('total', models.PositiveIntegerField(verbose_name='Total compra')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Germinar.producto')),
            ],
        ),
    ]
