# Generated by Django 4.0.4 on 2022-05-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Germinar', '0002_remove_cliente_contrasenna_alter_cliente_correoelect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio del producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idCliente',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id cliente'),
        ),
    ]
