# Generated by Django 4.0.4 on 2022-06-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Germinar', '0003_producto_imagenproducto_producto_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.CharField(choices=[('Y', 'SI'), ('N', 'NO')], default='N', max_length=1, verbose_name='Producto en oferta'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estadoCompra',
            field=models.CharField(choices=[('EE', 'En espera para despacho'), ('EC', 'En camino'), ('R', 'Recibido')], default='EE', max_length=2, verbose_name='Estado de la compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=1000, null=True, verbose_name='Descripcion producto'),
        ),
    ]
