# Generated by Django 4.0.5 on 2022-06-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Germinar', '0004_remove_producto_vendedor_producto_oferta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.PositiveIntegerField(max_length=150, primary_key=True, serialize=False, verbose_name='Id producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio del producto'),
        ),
    ]
