# Generated by Django 4.0.4 on 2022-06-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Germinar', '0006_remove_catproducto_idcategoria_catproducto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Germinar.catproducto'),
        ),
    ]
