# Generated by Django 4.0.4 on 2022-06-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Germinar', '0007_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catproducto',
            name='nombreCategoria',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre categoria'),
        ),
    ]
