# Generated by Django 4.0.4 on 2022-06-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Germinar', '0009_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[(1, 'Articulos de Jardinería'), (2, 'Plantas de interior'), (3, 'Plantas de exterior')], max_length=50),
        ),
    ]
