# Generated by Django 4.0.4 on 2022-06-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Germinar', '0010_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(choices=[(1, 'Articulos de Jardinería'), (2, 'Plantas de interior'), (3, 'Plantas de exterior')], on_delete=django.db.models.deletion.CASCADE, to='Germinar.catproducto'),
        ),
    ]
