# Generated by Django 4.0.4 on 2022-06-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Germinar', '0014_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Imagen del producto'),
        ),
    ]
