# Generated by Django 4.0.4 on 2022-06-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Germinar', '0015_alter_producto_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='suscripcion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='idCliente',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='idCompra',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='idProducto',
        ),
        migrations.DeleteModel(
            name='catSuscripcion',
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='compra',
        ),
        migrations.DeleteModel(
            name='detalleCompra',
        ),
    ]
