# Generated by Django 4.0.4 on 2022-07-03 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('tipoMembresia', models.CharField(choices=[('Gratis', 'free'), ('Germinar', 'ger')], default='Gratis', max_length=30)),
                ('precioMemebresia', models.IntegerField(default=3000)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMembresia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suscripcion.membresia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('userMembresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suscripcion.usermembresia')),
            ],
        ),
    ]
