# Generated by Django 4.0.4 on 2022-07-04 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembresia',
            name='tipoMembresia',
            field=models.ForeignKey(default='Gratis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suscripcion.membresia'),
        ),
    ]
